name: autograder-test
run-name: ${{ github.actor }} is running the autograder
on: [push]
jobs:
  run-install-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v4
      
      - run: chmod +x run
      - run: python3 checker.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Job Status
        run: echo "This job's status is ${{ job.status }}."
