name: Build and Deploy to Amplify

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Set to your Node.js version

    - name: Install Amplify CLI
      run: npm install -g @aws-amplify/cli

    - name: Configure Amplify
      run: amplify configure  # This step might require some interactive setup

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build-all  # Replace with your build command

    - name: Deploy to Amplify
      run: amplify push
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'your-aws-region'  # Set to your AWS region
